apiVersion: skaffold/v3
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: keepklicode/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: . 
  - image: keepklicode/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '**/*.js'
          dest: . 
  - image: keepklicode/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '**/*.js'
          dest: . 
  - image: keepklicode/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: . 
  - image: keepklicode/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: . 
  - image: keepklicode/payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: . 

manifests:
  rawYaml:
  - infra/k8s/auth-depl.yaml
  - infra/k8s/client-depl.yaml
  - infra/k8s/tickets-depl.yaml
  - infra/k8s/nats-depl.yaml
  - infra/k8s/orders-depl.yaml
  - infra/k8s/expiration-depl.yaml
  - infra/k8s/payments-depl.yaml
  - infra/k8s/ingress-srv.yaml